Fix issue with compilation on gcc 4.7.3
Trying to invoke this method causes compilation error on gcc 4.7.3.

When compiling following the line,

``` c++
video->template property<int>("width", 640)
```
an error occurs:

```
error: ‘template’ (as a disambiguator) is only allowed within templates

```

Compiling with 4.8.2 works though; looks like a gcc bug, so, until better days come...